name: Fetch GPR Data

on:
  workflow_dispatch:

jobs:
  fetch-gpr-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: "giovanonicris/geopolitics" 
          path: geopolitics 

      - name: Debug repository structure
        run: ls -R  #verify where script lives

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd geopolitics  # change directory to the repo folder
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch GPR data
        run: |
          cd geopolitics  # change directory to where fetch_gpr_data.py is located
          python fetch_gpr_data.py

      - name: Commit and push data
        run: |
          cd geopolitics  # change directory before git operates
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add gpr_data.csv
          git commit -m 'Update GPR data' || echo 'No changes to commit'
          git push
